# Generated by Django 4.2.5 on 2023-09-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_adduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddUser',
        ),
    ]
